### ISSUE TITLE
Clone and run repository

### ISSUE THREAD

**Issue by cgreggtcd** [SWENG15/ClassifyingUSLegislation#11]
Every team member should have the repository cloned and be able to run the web app.
Please comment on this to confirm you have done this

**Comment by cgreggtcd** [comment]
- [x] Alex Todeush
- [x] Claire Gregg
- [x] James O'Connell
- [ ] Noel Austin
- [x] Abigail O'Leary
- [ ] Fengchen Hu
- [ ] Finn Cummins
- [ ] Oisin Jago
- [ ] Kannan Sangeetha Nian Dravidan
- [ ] Yuuv Jauhari

**Comment by JamesOC3310** [comment]
Completed

**Comment by yjay18** [comment]
completed

**Comment by cgreggtcd** [comment]
All members confirmed to have repo working locally
