### ISSUE TITLE
Extract, transform and load initial data

### ISSUE THREAD

**Issue by cgreggtcd** [SWENG15/ClassifyingUSLegislation#13]
This does not necessitate setting up the pipeline at this point, getting some data ASAP for testing is the most important part. This will also give an idea of how the pipeline will be set up in future.

**User story:**
As a product designer, I would like to be able to work with a sample data set so that I can set up the machine learning classification algorithm.

**Comment by cgreggtcd** [comment]
For the first sprint, the intention is to manually create a CSV file with the text of a bill and its subject matter.

@alex-todeush if you could close this issue (and potentially link the pull request) when you've done this?

**Comment by alex-todeush** [comment]
A basic version of the ETL is finished now, you can define your search, get the results and populate a csv file with the ID, Title, Text and Status of the resulting bills
