### ISSUE TITLE
Extraction of Data

### ISSUE THREAD

**Issue by cgreggtcd** [SWENG15/ClassifyingUSLegislation#3]
This is the first part of the ETL pipeline - extracting the data.

This involves 
1. Deciding where to extract data from
2. What way to extract the data - API, or another way
3. Making the data accessible to the next stage of the pipeline - Transform

**User story:**
As a product designer, I want to have a way to extract data about legislation easily so that I can add more data to the machine learning model.

**Comment by alex-todeush** [comment]
1. The data is being extracted from legiscan.com
2. Their API is being used along with a library called pylegiscan which allows easy interfacing with it using Python
3. The search result comes in as a list of Bill IDs. These can then be individually queried which returns a JSON object.
