### ISSUE TITLE
Transformation of Data

### ISSUE THREAD

**Issue by cgreggtcd** [SWENG15/ClassifyingUSLegislation#4]
This is the second part of the ETL pipeline, transforming the data into the appropriate form.

This will require several parts:
1. Deciding what parts of the data are relevant.
2. Getting the data from where it has been extracted to.
3. Transforming the data into the appropriate form

**User story:**
As a product designer, I want to have an automated way to transform data about legislation into the correct format so that I can automatically and easily add training data to the machine learning model.

**Comment by alex-todeush** [comment]
1. For now we are using ['ID', 'Title', 'Text', 'Status', 'Subject'] as the relevant data fields.
2. We are getting the data from the JSON returned for the requests.
3. The data is being transformed into a csv containing only the specified data fields
