### ISSUE TITLE
Loading of Data

### ISSUE THREAD

**Issue by cgreggtcd** [SWENG15/ClassifyingUSLegislation#5]
This is the final part of the ETL pipeline.

This will involve loading the data from its transformation into the ML classification model, in the appropriate format.

**User story:**
As a product designer, I want to have an automatic pipeline to load data into the ML classification model so that it is easy to train the model more.

**Comment by alex-todeush** [comment]
We have implemented a working system to import the csv dataset files into the ML models. This allows training based on the information gathered by the ETL team.
