### ISSUE TITLE
Add test for at least one pass/fail

### ISSUE THREAD

**Issue by cgreggtcd** [SWENG15/ClassifyingUSLegislation#87]
Add tests for each dataset to confirm there is at least one of each necessary type of bill in each dataset - i.e. for the probability of passing dataset, ensure there is at least 1 fail/veto, and at least 1 pass.

**Comment by alex-todeush** [comment]
Added code to assert that each dataset that has one bill with Status - 'Passed' and one with 'Vetoed' or 'Failed'.
